name: Download Specific Cache

on:
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  download-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Restore the cache you want
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: .
          key: ximera-main-a6baae8a83be8e55be8c8132ec6ad24a8f4c5ed0

      # Upload the restored cache as an artifact
      - name: Upload Cache as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-cache
          path: .