name: Ximera Workflow

on:
  push:
    branches:
      - 'split'

env:
  GPG_KEY: ${{ secrets.GPG_KEY }}
  GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
  XIMERA_NAME: wimcalc20250904
  XIMERA_URL: "https://xerxes.ximera.org/"
  XM_TO_PROCESS: "testxourse.tex"

jobs:

  build-ximera-pdfexport:
    name: Run pdfexport
    runs-on: ubuntu-latest
    continue-on-error: true
    container: &x-container
      image: ghcr.io/ximeraproject/ximeralatex:v2.7.5fix2
      options: >-
        --workdir /code
    permissions:
      actions: read
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache/restore@v4
        with:
          path: |
            build/**
            **/*.pdf
            **/*.html
            **/*.aux
            **/*.log
            **/*.toc
            **/*.xref
            **/*.svg
            **/*.png
            !.git/**
            !.github/**
          key: ximeraPDF-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ximeraPDF-${{ github.ref_name }}-
            ximeraPDF-

      - run: |
            pwd
            ls -alrt
            type xmlatex
            env
            git config --global --add safe.directory /code
            git config --global --add safe.directory /__w/calculus/calculus
            ls -al /usr/local/bin/
            ls -al /root/texmf
            find /root/texmf
            id
            chmod  +rx /root
            df -h
            ls -al /root
            kpsewhich -var-value=TEXMFHOME
            export TEXMFHOME=/root/texmf
            kpsewhich -var-value=TEXMFHOME
            export LUA_PATH="/root/texmf/tex/latex/ximeraLatex/luaxake/?.lua;;"
            echo $LUA_PATH
            strace -o brol -f luaxake -h || echo NOK
            grep luaxake brol
            xmlatex bake --compile pdfexport -j 5 $XM_TO_PROCESS

      - uses: actions/cache/save@v4
        with:
          path: |
            build/**
            **/*.pdf
            **/*.html
            **/*.aux
            **/*.log
            **/*.toc
            **/*.xref
            **/*.svg
            **/*.png
            !.git/**
            !.github/**
          key: ximeraPDF-${{ github.ref_name }}-${{ github.sha }}

      - uses: actions/upload-artifact@v4
        with:
          name: pdfexport
          path: .

  build-ximera-htmlexport:
    name: Run htmlexport
    needs: build-ximera-pdfexport
    runs-on: ubuntu-latest
    continue-on-error: true
    container: *x-container
    permissions:
      actions: read
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache/restore@v4
        with:
          path: |
            build/**
            **/*.pdf
            **/*.html
            **/*.aux
            **/*.log
            **/*.toc
            **/*.xref
            **/*.svg
            **/*.png
            !.git/**
            !.github/**
          key: ximeraPDF-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ximeraPDF-${{ github.ref_name }}-
            ximeraPDF-

      - run: |
            git config --global --add safe.directory /code
            git config --global --add safe.directory /__w/calculus/calculus
            export TEXMFHOME=/root/texmf
            pwd
            xmlatex bake --compile htmlexport -j 5 $XM_TO_PROCESS

      - uses: actions/cache/save@v4
        with:
          path: |
            build/**
            **/*.pdf
            **/*.html
            **/*.aux
            **/*.log
            **/*.toc
            **/*.xref
            **/*.svg
            **/*.png
            !.git/**
            !.github/**
          key: ximeraHTML-${{ github.ref_name }}-${{ github.sha }}

      - uses: actions/upload-artifact@v4
        with:
          name: htmlexport
          path: .

  build-ximera-serve:
    name: Run frost/serve preview
    needs: build-ximera-htmlexport
    continue-on-error: true
    runs-on: ubuntu-latest
    container: *x-container
    permissions:
      actions: read
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache/restore@v4
        with:
          path: |
            build/**
            **/*.pdf
            **/*.html
            **/*.aux
            **/*.log
            **/*.toc
            **/*.xref
            **/*.svg
            **/*.png
            !.git/**
            !.github/**
          key: ximeraHTML-${{ github.ref_name }}-${{ github.sha }}

      - run: |
            git config --global --add safe.directory /code
            git config --global --add safe.directory /__w/calculus/calculus
            export TEXMFHOME=/root/texmf
            pwd
            xmlatex name
            xmlatex frost $XM_TO_PROCESS
            xmlatex serve $XM_TO_PROCESS
            echo "✅ Published to $XIMERA_URL$XIMERA_NAME " >> $GITHUB_STEP_SUMMARY


      - uses: actions/cache/save@v4
        with:
          path: |
            xmScripts/**
            .git/**
          key: ximeraSERVE-${{ github.ref_name }}-${{ github.sha }}

      - uses: actions/upload-artifact@v4
        with:
          name: serve
          path: .

  publish-ximera:
    name: Run serve to mooculus
    needs: build-ximera-serve
    runs-on: ubuntu-latest
    continue-on-error: true
    container: *x-container
    environment: production

    steps:
      - uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          path: |
            xmScripts/**
            .git/**
          key: ximeraSERVE-${{ github.ref_name }}-${{ github.sha }}

      - run: |
            echo "Serving to $XIMERA_URL$XIMERA_NAME"
            git config --global --add safe.directory /code
            git config --global --add safe.directory /__w/calculus/calculus
            export TEXMFHOME=/root/texmf
            xmlatex name
            xmlatex serve -t $XM_TO_PROCESS
            echo "Recent git log:"
            git log --oneline --graph --decorate --all -n 10
            echo "✅ Published to $XIMERA_URL$XIMERA_NAME " >> $GITHUB_STEP_SUMMARY
        env:
          XIMERA_URL: "https://xerxes.ximera.org/"
          XIMERA_NAME: "calculus"
