name: Ximera Workflow

on:
  push:
    branches:
      - 'split'

env:
  GPG_KEY: ${{ secrets.GPG_KEY }}
  GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
  XIMERA_NAME: wimcalc20250904
  XIMERA_URL: "https://xerxes.ximera.org/"
  XM_TO_PROCESS: "testxourse.tex"

# YAML anchor for the container image
x-container: &x-container
  image: ghcr.io/ximeraproject/ximeralatex:v2.7.5fix2

jobs:
  build-ximera-pdfexport:
    name: Build pdfexport
    runs-on: ubuntu-latest
    container: *x-container
    steps:
      - uses: actions/checkout@v4
      - run: ./xmScripts/xmlatex bake --compile pdfexport -j 5 $XM_TO_PROCESS

  build-ximera-htmlexport:
    name: Build htmlexport
    needs: build-ximera-pdfexport
    runs-on: ubuntu-latest
    container: *x-container
    steps:
      - uses: actions/checkout@v4
      - run: ./xmScripts/xmlatex bake --compile htmlexport -j 5 $XM_TO_PROCESS

  build-ximera-serve:
    name: Serve
    needs: build-ximera-htmlexport
    runs-on: ubuntu-latest
    container: *x-container
    steps:
      - uses: actions/checkout@v4
      - run: ./xmScripts/xmlatex name
      - run: ./xmScripts/xmlatex frost $XM_TO_PROCESS 
      - run: ./xmScripts/xmlatex serve $XM_TO_PROCESS

  publish-ximera:
    name: Publish
    needs: build-ximera-serve
    runs-on: ubuntu-latest
    container: *x-container
    steps:
      - run: ./xmScripts/xmlatex serve -t $XM_TO_PROCESS
